package com.modulus.uno.paysheet

enum DeductionType {

  D001 ('001','Seguridad social', 'G'),
  D002 ('002','ISR', 'G'),
  D003 ('003','Aportaciones a retiro, cesantía en edad avanzada y vejez.', 'G'),
  D004 ('004','Otros', 'G'),
  D005 ('005','Aportaciones a Fondo de vivienda', 'G'),
  D006 ('006','Descuento por incapacidad', 'G'),
  D007 ('007','Pensión alimenticia', 'G'),
  D008 ('008','Renta', 'G'),
  D009 ('009','Préstamos provenientes del Fondo Nacional de la Vivienda para los Trabajadores', 'G'),
  D010 ('010','Pago por crédito de vivienda', 'G'),
  D011 ('011','Pago de abonos INFONACOT', 'G'),
  D012 ('012','Anticipo de salarios', 'G'),
  D013 ('013','Pagos hechos con exceso al trabajador', 'G'),
  D014 ('014','Errores', 'G'),
  D015 ('015','Pérdidas', 'G'),
  D016 ('016','Averías', 'G'),
  D017 ('017','Adquisición de artículos producidos por la empresa o establecimiento', 'G'),
  D018 ('018','Cuotas para la constitución y fomento de sociedades cooperativas y de cajas de ahorro', 'G'),
  D019 ('019','Cuotas sindicales', 'G'),
  D020 ('020','Ausencia (Ausentismo)', 'G'),
  D021 ('021','Cuotas obrero patronales', 'G'),
  D022 ('022','Impuestos Locales', 'G'),
  D023 ('023','Aportaciones voluntarias', 'G'),
  D024 ('024','Ajuste en Gratificación Anual (Aguinaldo) Exento', 'G'),
  D025 ('025','Ajuste en Gratificación Anual (Aguinaldo) Gravado', 'G'),
  D026 ('026','Ajuste en Participación de los Trabajadores en las Utilidades PTU Exento', 'G'),
  D027 ('027','Ajuste en Participación de los Trabajadores en las Utilidades PTU Gravado', 'G'),
  D028 ('028','Ajuste en Reembolso de Gastos Médicos Dentales y Hospitalarios Exento', 'G'),
  D029 ('029','Ajuste en Fondo de ahorro Exento', 'G'),
  D030 ('030','Ajuste en Caja de ahorro Exento', 'G'),
  D031 ('031','Ajuste en Contribuciones a Cargo del Trabajador Pagadas por el Patrón Exento', 'G'),
  D032 ('032','Ajuste en Premios por puntualidad Gravado', 'G'),
  D033 ('033','Ajuste en Prima de Seguro de vida Exento', 'G'),
  D034 ('034','Ajuste en Seguro de Gastos Médicos Mayores Exento', 'G'),
  D035 ('035','Ajuste en Cuotas Sindicales Pagadas por el Patrón Exento', 'G'),
  D036 ('036','Ajuste en Subsidios por incapacidad Exento', 'G'),
  D037 ('037','Ajuste en Becas para trabajadores y/o hijos Exento', 'G'),
  D038 ('038','Ajuste en Horas extra Exento', 'G'),
  D039 ('039','Ajuste en Horas extra Gravado', 'G'),
  D040 ('040','Ajuste en Prima dominical Exento', 'G'),
  D041 ('041','Ajuste en Prima dominical Gravado', 'G'),
  D042 ('042','Ajuste en Prima vacacional Exento', 'G'),
  D043 ('043','Ajuste en Prima vacacional Gravado', 'G'),
  D044 ('044','Ajuste en Prima por antigüedad Exento', 'G'),
  D045 ('045','Ajuste en Prima por antigüedad Gravado', 'G'),
  D046 ('046','Ajuste en Pagos por separación Exento', 'G'),
  D047 ('047','Ajuste en Pagos por separación Gravado', 'G'),
  D048 ('048','Ajuste en Seguro de retiro Exento', 'G'),
  D049 ('049','Ajuste en Indemnizaciones Exento', 'G'),
  D050 ('050','Ajuste en Indemnizaciones Gravado', 'G'),
  D051 ('051','Ajuste en Reembolso por funeral Exento', 'G'),
  D052 ('052','Ajuste en Cuotas de seguridad social pagadas por el patrón Exento', 'G'),
  D053 ('053','Ajuste en Comisiones Gravado', 'G'),
  D054 ('054','Ajuste en Vales de despensa Exento', 'G'),
  D055 ('055','Ajuste en Vales de restaurante Exento', 'G'),
  D056 ('056','Ajuste en Vales de gasolina Exento', 'G'),
  D057 ('057','Ajuste en Vales de ropa Exento', 'G'),
  D058 ('058','Ajuste en Ayuda para renta Exento', 'G'),
  D059 ('059','Ajuste en Ayuda para artículos escolares Exento', 'G'),
  D060 ('060','Ajuste en Ayuda para anteojos Exento', 'G'),
  D061 ('061','Ajuste en Ayuda para transporte Exento', 'G'),
  D062 ('062','Ajuste en Ayuda para gastos de funeral Exento', 'G'),
  D063 ('063','Ajuste en Otros ingresos por salarios Exento', 'G'),
  D064 ('064','Ajuste en Otros ingresos por salarios Gravado', 'G'),
  D065 ('065','Ajuste en Jubilaciones, pensiones o haberes de retiro Exento', 'G'),
  D066 ('066','Ajuste en Jubilaciones, pensiones o haberes de retiro Gravado', 'G'),
  D067 ('067','Ajuste en Pagos por separación Acumulable', 'G'),
  D068 ('068','Ajuste en Pagos por separación No acumulable', 'G'),
  D069 ('069','Ajuste en Jubilaciones, pensiones o haberes de retiro Acumulable', 'G'),
  D070 ('070','Ajuste en Jubilaciones, pensiones o haberes de retiro No acumulable', 'G'),
  D071 ('071','Ajuste en Subsidio para el empleo (efectivamente entregado al trabajador)', 'G'),
  D072 ('072','Ajuste en Ingresos en acciones o títulos valor que representan bienes Exento', 'G'),
  D073 ('073','Ajuste en Ingresos en acciones o títulos valor que representan bienes Gravado', 'G'),
  D074 ('074','Ajuste en Alimentación Exento', 'G'),
  D075 ('075','Ajuste en Alimentación Gravado', 'G'),
  D076 ('076','Ajuste en Habitación Exento', 'G'),
  D077 ('077','Ajuste en Habitación Gravado', 'G'),
  D078 ('078','Ajuste en Premios por asistencia', 'G'),
  D079 ('079','Ajuste en Pagos distintos a los listados y que no deben considerarse como ingreso por sueldos, salarios o ingresos asimilados.', 'G'),
  D080 ('080','Ajuste en Viáticos gravados', 'G'),
  D081 ('081','Ajuste en Viáticos (entregados al trabajador)', 'G'),
  D082 ('082','Ajuste en Fondo de ahorro Gravado', 'G'),
  D083 ('083','Ajuste en Caja de ahorro Gravado', 'G'),
  D084 ('084','Ajuste en Prima de Seguro de vida Gravado', 'G'),
  D085 ('085','Ajuste en Seguro de Gastos Médicos Mayores Gravado', 'G'),
  D086 ('086','Ajuste en Subsidios por incapacidad Gravado', 'G'),
  D087 ('087','Ajuste en Becas para trabajadores y/o hijos Gravado', 'G'),
  D088 ('088','Ajuste en Seguro de retiro Gravado', 'G'),
  D089 ('089','Ajuste en Vales de despensa Gravado', 'G'),
  D090 ('090','Ajuste en Vales de restaurante Gravado', 'G'),
  D091 ('091','Ajuste en Vales de gasolina Gravado', 'G'),
  D092 ('092','Ajuste en Vales de ropa Gravado', 'G'),
  D093 ('093','Ajuste en Ayuda para renta Gravado', 'G'),
  D094 ('094','Ajuste en Ayuda para artículos escolares Gravado', 'G'),
  D095 ('095','Ajuste en Ayuda para anteojos Gravado', 'G'),
  D096 ('096','Ajuste en Ayuda para transporte Gravado', 'G'),
  D097 ('097','Ajuste en Ayuda para gastos de funeral Gravado', 'G'),
  D098 ('098','Ajuste a ingresos asimilados a salarios gravados', 'G'),
  D099 ('099','Ajuste a ingresos por sueldos y salarios gravados', 'G'),
  D100 ('100','Ajuste en Viáticos exentos', 'G'),
  D101 ('101','ISR Retenido de ejercicio anterior', 'G')

  private final String key
  private final String description
  private final String type

  PerceptionType(String key, String description, String type) {
    this.key = key
    this.description = description
    this.type = type
  }

  String toString() {
    "${this.key} - ${this.description}"
  }

}
