package com.modulus.uno.paysheet

enum PaysheetEmployeeStatus {
  PENDING, PAYED, CANCELED, REJECTED, IMSS_PAYED, ASSIMILABLE_PAYED, IMSS_STAMPED_XML, IMSS_STAMPED, ASSIMILABLE_STAMPED_XML, ASSIMILABLE_STAMPED, FULL_STAMPED_XML, FULL_STAMPED_XML_IMSS_PDF, FULL_STAMPED_XML_ASSIMILABLE_PDF, FULL_STAMPED
}
