databaseChangeLog = {

    changeSet(author: "temoc (generated)", id: "1539020035002-1") {
        addColumn(tableName: "bank") {
            column(name: "rfc", type: "varchar(12)")
        }
    }

  changeSet(author: "temoc (manual)", id: "updating-rfc-for-banks") {
    grailsChange {
      change {
        sql.execute("update bank set rfc='BNM840515VB1' where substring(banking_code, 3, 3)='002'")
        sql.execute("update bank set rfc='BNC8507311M4' where substring(banking_code, 3, 3)='006'")
        sql.execute("update bank set rfc='BNO670315CD0' where substring(banking_code, 3, 3)='009'")
        sql.execute("update bank set rfc='BBA830831LJ2' where substring(banking_code, 3, 3)='012'")
        sql.execute("update bank set rfc='BSM970519DU8' where substring(banking_code, 3, 3)='014'")
        sql.execute("update bank set rfc='BNE820901682' where substring(banking_code, 3, 3)='019'")
        sql.execute("update bank set rfc='HMI950125KG8' where substring(banking_code, 3, 3)='021'")
        sql.execute("update bank set rfc='BBA940707IE1' where substring(banking_code, 3, 3)='030'")
        sql.execute("update bank set rfc='IBA950503GTA' where substring(banking_code, 3, 3)='032'")
        sql.execute("update bank set rfc='BII931004P61' where substring(banking_code, 3, 3)='036'")
        sql.execute("update bank set rfc='BIN931011519' where substring(banking_code, 3, 3)='037'")
        sql.execute("update bank set rfc='BMI9312038R3' where substring(banking_code, 3, 3)='042'")
        sql.execute("update bank set rfc='SIN9412025I4' where substring(banking_code, 3, 3)='044'")
        sql.execute("update bank set rfc='BRM940216EQ6' where substring(banking_code, 3, 3)='058'")
        sql.execute("update bank set rfc='BIN940223KE0' where substring(banking_code, 3, 3)='059'")
        sql.execute("update bank set rfc='BAN950525MD6' where substring(banking_code, 3, 3)='060'")
        sql.execute("update bank set rfc='BAF950102JP5' where substring(banking_code, 3, 3)='062'")
        sql.execute("update bank set rfc='BMN930209927' where substring(banking_code, 3, 3)='072'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='102'")         
        sql.execute("update bank set rfc='AEB960223JP7' where substring(banking_code, 3, 3)='103'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='106'")       
        sql.execute("update bank set rfc='BTM960401DV7' where substring(banking_code, 3, 3)='108'")
        sql.execute("update bank set rfc='BJP950104LJ5' where substring(banking_code, 3, 3)='110'")
        sql.execute("update bank set rfc='BMI9704113PA' where substring(banking_code, 3, 3)='112'")
        sql.execute("update bank set rfc='BVM951002LX0' where substring(banking_code, 3, 3)='113'")
        sql.execute("update bank set rfc='IBM951129P29' where substring(banking_code, 3, 3)='116'")
        sql.execute("update bank set rfc='DBM000228J35' where substring(banking_code, 3, 3)='124'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='126'")         
        sql.execute("update bank set rfc='BAI0205236Y8' where substring(banking_code, 3, 3)='127'")
        sql.execute("update bank set rfc='BAM0511076B3' where substring(banking_code, 3, 3)='128'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='129'")
        sql.execute("update bank set rfc='BCI001030ECA' where substring(banking_code, 3, 3)='130'")
        sql.execute("update bank set rfc='BAF060524EV6' where substring(banking_code, 3, 3)='131'")
        sql.execute("update bank set rfc='BMI061005NY5' where substring(banking_code, 3, 3)='132'")
        sql.execute("update bank set rfc='PBI061115SC6' where substring(banking_code, 3, 3)='133'")
        sql.execute("update bank set rfc='BWM0611132A9' where substring(banking_code, 3, 3)='134'")
        sql.execute("update bank set rfc='NFI3406305T0' where substring(banking_code, 3, 3)='135'")
        sql.execute("update bank set rfc='IBI061030GD4' where substring(banking_code, 3, 3)='136'")
        sql.execute("update bank set rfc='BSI061110963' where substring(banking_code, 3, 3)='137'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='138'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='139'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='140'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='141'")
        sql.execute("update bank set rfc='CIB850918BN8' where substring(banking_code, 3, 3)='143'")
        sql.execute("update bank set rfc='BBS110906HD3' where substring(banking_code, 3, 3)='145'")
        sql.execute("update bank set rfc='BAN500901167' where substring(banking_code, 3, 3)='166'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='168'")
        sql.execute("update bank set rfc='MCB860313CD6' where substring(banking_code, 3, 3)='600'")
        sql.execute("update bank set rfc='GGB080116EZ0' where substring(banking_code, 3, 3)='601'")
        sql.execute("update bank set rfc='MCC860715J45' where substring(banking_code, 3, 3)='602'")
        sql.execute("update bank set rfc='VCC920820FQ4' where substring(banking_code, 3, 3)='605'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='606'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='607'")
        sql.execute("update bank set rfc='VCB870729PH6' where substring(banking_code, 3, 3)='608'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='610'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='614'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='615'")
        sql.execute("update bank set rfc='CBF920629BV0' where substring(banking_code, 3, 3)='616'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='617'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='618'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='619'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='620'")
        sql.execute("update bank set rfc='ACB7609076M2' where substring(banking_code, 3, 3)='621'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='622'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='623'")
        sql.execute("update bank set rfc='DSC950118SX2' where substring(banking_code, 3, 3)='626'")
        sql.execute("update bank set rfc='ZSE950306M48' where substring(banking_code, 3, 3)='627'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='628'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='629'")
        sql.execute("update bank set rfc='ICB061106G80' where substring(banking_code, 3, 3)='630'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='631'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='632'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='633'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='634'")
        sql.execute("update bank set rfc='HSE701218532' where substring(banking_code, 3, 3)='636'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='637'")
        sql.execute("update bank set rfc='AKA060427QP2' where substring(banking_code, 3, 3)='638'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='640'")
        sql.execute("update bank set rfc='ORR920530QL5' where substring(banking_code, 3, 3)='642'")
        sql.execute("update bank set rfc='STP081030FE6' where substring(banking_code, 3, 3)='646'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='647'")
        sql.execute("update bank set rfc='PCB050107CP2' where substring(banking_code, 3, 3)='648'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='649'")
        sql.execute("update bank set rfc='SMN930802FN9' where substring(banking_code, 3, 3)='651'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='652'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='653'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='655'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='656'")
        sql.execute("update bank set rfc='OEN040430H19' where substring(banking_code, 3, 3)='659'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='901'")
        sql.execute("update bank set rfc='null' where substring(banking_code, 3, 3)='902'")
        sql.execute("update bank set rfc='LSF970101N35' where substring(banking_code, 3, 3)='670'")
      }
    }
  }

}
