package com.modulus.uno.status

enum SaleOrderStatus {
  CREADA,
  POR_AUTORIZAR,
  AUTORIZADA,
  RECHAZADA,
  PAGADA,
  EJECUTADA,
  CANCELADA,
  CANCELACION_POR_AUTORIZAR,
  CANCELACION_AUTORIZADA,
  CANCELACION_EJECUTADA,
  GENERANDO_XML,
  XML_GENERADO
}
